#Problem: ChatGPT 활용하여 배열생성
😄 다음과 같은 결과가 나오도록 배열을 생성하시오.
```
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 ```

# Problem: ChatGPT 활용하여 배열생성
😄 다음과 같은 결과가 나오도록 배열을 생성하시오.
```
[[[ 74  79  84  89]
  [ 94  99 104 109]
  [114 119 124 129]]

 [[134 139 144 149]
  [154 159 164 169]
  [174 179 184 189]]

 [[194 199 204 209]
  [214 219 224 229]
  [234 239 244 249]]]
 ```

#Problem: ChatGPT 활용하여 대통령 평균 신장 구하기
- 배열에서 다음을 구하시오.

```
Mean height: 180.05
Standard deviation: 6.98
Minimum height: 163.0
Maximum height: 193.0
```


In [ ]:
ar = np.array([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173.,
       173., 175., 178., 183., 193., 178., 173., 174., 183., 183., 168.,
       170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183.,
       193., 182., 183., 177., 185., 188., 188., 182., 185., 191., 182.])

# Problem: 가중치 적용하여 성적구하기
- 다음과 같은 배열이 있다.
- 자료는 앞에서부터 학번, 영어, 국어, 수학, 체육, 컴퓨터의 시험점수이다.
1. 전체 평균점수가 가장 높은 학생의 번호는?
2. 전체 평균점수가 가장 낮은 학생의 번호는?
3. 국어, 영어, 수학 점수의 평균이 가장 높은 학생의 번호는?
4. 국어, 영어, 수학 점수에 2배 가중치를 준다면 5과목의 평균 점수가 가장 높은 학생의 번호는?

Output Samples
1. 20232
2. 20237
3. 20232
4. 20232

In [ ]:
import numpy as np
scores=np.array([[20231., 70., 85., 95., 100., 100.],
          [20232., 100., 85., 90., 90., 95.],
          [20233., 95., 95., 80., 75., 75.],
          [20234., 65., 75., 70., 90., 100.],
          [20235., 90., 80., 85., 95., 95.],
          [20236., 90., 90., 75., 75., 80.],
          [20237., 60., 90., 80., 40., 45.],
          [20238., 85., 90., 75., 60., 90.],
          [20239., 90., 85., 85., 90., 85.]])
scores