# Day-3: 수치형데이터 연산

# I. numpy

- numpy는 Number와 python의 합성어이다.
- 행렬이나 대규모 다차원 배열을 쉽고 빠르게 처리할 수 있도록 하는 파이썬 라이브러리이며, 간단한 기능부터 계산과학 분야의 복잡한 연산을 지원하기 위한 기능들까지 포함되어 있다.
- 행렬은 행과 열이 있는 것
- 배열은 행렬을 여러개 쌓아올린 것
- 배열은 데이터의 묶음이다.
- numpy의 배열에는 모두 동일한 자료형만 저장이 가능하다.

- numpy를 사용하기 위해서는 import로 모듈을 불러와야한다.
- 공공연한 약속처럼 numpy모듈은 보통 np라는 별칭으로 불리운다.
- 별칭은 as라는 키워드를 사용하여 만든다.

In [ ]:
import numpy as np

## 1-D array 생성하기(벡터)

- 1차원 배열부터 만들어보자.
- 파이썬에서는 배열을 생성하는 다양한 방법을 지원한다.
  - numpy 모듈의 `array()`를 통해 배열을 만들 수 있다.
  - numpy 모듈의 `arange()`를 통해 배열을 만들 수 있다.


```
np.array(리스트 or range())
np.arange(start, end, step)
```



In [ ]:
ar1 = np.array([1,2,3,4,5])
ar11 = np.array(range(10))
ar111= np.arange(1,6)
print(ar1)
print(ar11)
print(ar111)

## 2-D array 생성하기(메트릭스, 행렬)

- 2차원 배열은 행(Row)과 열(Column)로 구성되어 있다.
<div align="center"><img src="https://haesunbyun.github.io/AISW/_images/ch11/array.png" style="width:400px;"></div>
- 행은 가로 방향으로 줄을 세운 것이며, 열은 세로 방향으로 줄을 세운 것이다.
- 2차원 배열은 array()에 중첩 리스트를 넣어주거나, 배열모양을 바꿔주는 reshape()을 통해서 생성할 수 있다.

```
np.array([리스트 of 리스트])
np.arange(start,end,step).reshape(row, column)
```
- 여기서 row는 행의 개수, column은 열의 개수이다. column을 -1로 써주면 각 행에 들어갈 데이터를 동일하게 적용해준다.

- 이때 배열 원소의 개수와 row*column의 개수가 같아야 한다.



In [ ]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
ar22 = np.arange(1,13).reshape(4,3)
ar222 = ar2.reshape(3,-1)
print(ar2)
print(ar22)

## Problem: 배열생성
😄 다음과 같은 결과가 나오도록 배열을 생성하시오.
```
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 ```

## 3-D array 생성하기(텐서)
- 3차원 배열은 면(page), 행, 열을 가진다.
- 생성하는 방법은 2차원 배열과 유사하지만 리스트가 3번 중첩된다.

```
np.array([리스트 of 리스트 of 리스트])
np.arange(start,end,step).reshape(page, row, column)
```

In [ ]:
ar3 = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])
print(ar3)

## 배열 속성 확인하기

- 배열의 구성, 차수 등의 정보를 확인하기 위해서는 다음과 같은 변수를 쓸 수 있다.

```
배열명.ndim
배열명.shape
배열명.size
배열명.dtype
```
  - ndim: 배열의 축 또는 차원의 개수
  - shape: 배열의 모양이며, (m,n)형식으로 나타난다.
  - size: 배열 원소의 개수. shape내의 원소의 크기의 곱과 같다. 즉 shape의 m*n은 size와 같다.
  - dtype: 배열의 데이터타입을 나타낸다.

In [ ]:
print(ar3.ndim)
print(ar3.shape)
print(ar3.size)
print(ar3.dtype)

## Problem : 배열생성
😄 다음과 같은 결과가 나오도록 배열을 생성하시오.
```
[[[ 74  79  84  89]
  [ 94  99 104 109]
  [114 119 124 129]]

 [[134 139 144 149]
  [154 159 164 169]
  [174 179 184 189]]

 [[194 199 204 209]
  [214 219 224 229]
  [234 239 244 249]]]
 ```

## 인덱싱
- 1차원 배열을 인덱싱하는 것은 리스트와 동일하다.


In [ ]:
ar=np.arange(12)
print(ar, '\n\n===결과===')
print(ar[5])

- 2차원 배열을 인덱싱하는 방법은 대괄호를 연속하여 쓰고 인덱스를 각각 넣거나 하나의 대괄호에 콤마로 구분하여 인덱스를 넣어준다.
    - 배열명[행인덱스][열인덱스]
    - 배열명[행인덱스,열인덱스]  

- 대괄호를 연속하여 쓰면 가장 앞 대괄호부터 인덱싱 또는 슬라이싱 해서 나온 결과를 가지고 다음 대괄호의 인덱싱 또는 슬라이싱을 차례대로 한다.
즉, 앞의 대괄호에서 나온 결과가 작업범위의 대상이 된다.
- 예를 들어, 아래와 같다.

```python
 ar2 = ar[1]
 ar3 = ar2[2]
 ar3 == ar[1][2]
```
- 대괄호를 하나 쓰는 것은 작업범위가 배열 전체를 대상으로 한다.
- 인덱싱에서는 대괄호를 연속으로 써는 방법이나 하나의 대괄호에 콤마로 구분하여 쓰는 방법이나 인덱싱의 결과는 똑같다. 그러나 슬라이싱에서는 그 결과가 달라진다.

In [ ]:
ar=np.arange(12).reshape(4,3)
print(ar, '\n\n===결과===')
print(ar[1][2])
print(ar[1,2])

In [ ]:
ar=np.arange(12).reshape(4,3)
ar2 = ar[1]
ar3 = ar2[2]
ar3 == ar[1][2]

- 3차원의 경우에도 2차원에서와 마찬가지로 면, 행, 열 순서로 사용하면 된다.

In [ ]:
ar=np.arange(12).reshape(2,2,3)
print(ar, '\n\n===결과===')
print(ar[1][1][2])
print(ar[1,1,2])

## 슬라이싱
- 슬라이싱의 경우에는 대괄호를 연속으로 사용하는 것과 하나의 대괄호에 콤마로 나열하는 것의 결과가 다를 수도 있다.

In [ ]:
ar=np.arange(12).reshape(3,4)
print(ar)
print('\n\n===연속된 대괄호 결과===')
print(ar[1:][1:])
print('\n\n===하나의 대괄호 결과===')
print(ar[1:, 1:])

- 위의 코드에서 ar[1:]의 결과는 아래와 같다.

```
 [[ 4  5  6  7]
 [ 8  9 10 11]]
```
- 이 결과를 변수 a에 저장했다면 ar[1:][1:]는 a[1:]와 같다. 즉, a의 1행부터 끝까지 이므로 [ 8  9 10 11]을 슬라이싱 한다.

- ar[1:, 1:]는 ar 전체를 대상으로 작업하므로 행은 1행부터 끝까지, 그 범위에서 열이 1열부터 끝까지를 슬라이싱한다.

## Problem : 슬라이싱
😄 0부터 14까지 원소를 갖는 3행 5열의 2차원 배열을 만드시오.
만든 2차원 배열에서 아래 부분배열을 슬라이싱하시오.
```
[[6,7,8,9],
 [11,12,13,14]]
```

## Problem : 슬라이싱
😄 0부터 23까지 원소를 갖는 3면, 2행, 4열의 3차원 배열을 만드시오.
만든 3차원 배열에서 아래 부분배열을 슬라이싱하시오.
```
[[16,17,18,19],
 [20,21,22,23]]
```

- ar[1:, 0:, :3] 슬라이싱 결과를 확인하시오.

## Numpy 응용: 그래프 그리기

- numpy로 만든 배열은 다양한 목적을 위해 사용되지만 선형 그래프를 그리기 위해 배열을 활용하는 하나의 예를 보도록 하자.
- 그래프를 그리기 위한 수식은 다음과 같다.

> $y=2x^2-3x+1$


- 차후에 배우겠지만, 파이썬으로 그래프를 그리기 위해서는 matplotlib.pyplot 모듈을 불러와야 한다.
- matplotlib.pyplot 모듈은 보통 plt라는 별칭으로 불리운다.
- plt의 plot()은 선형그래프를 그리는 함수이다.
- 파이썬에서는 그래프를 그렸다고 해서 화면에 바로 보여주지 않는다. plt.show()는 그래프를 화면에 보여주는 함수이다.


```
plt.plot(x축 데이터, y축 데이터)
```

In [ ]:
import matplotlib.pyplot as plt
x = np.arange(0, 5, 0.1)
#todo

## Numpy 응용: 데이터 분석

배열의 응용
- 데이터 분석 예: 날씨 데이터를 분석. 특정 기간 동안의 온도 데이터를 분석해 평균, 최대, 최소 값을 계산

In [ ]:
import numpy as np

# 예제: 일주일간의 온도 데이터 (섭씨)
temperatures = np.array([22.1, 23.4, 21.8, 22.9, 23.0, 24.2, 23.5])

# 평균 온도
mean_temp = np.mean(temperatures)

# 최대 온도
max_temp = np.max(temperatures)

# 최소 온도
min_temp = np.min(temperatures)

print(f"평균 온도: {mean_temp:.2f}°C")
print(f"최대 온도: {max_temp:.2f}°C")
print(f"최소 온도: {min_temp:.2f}°C")


## Numpy 응용: 이미지 처리하기

- 이미지 처리의 예: 이미지를 흑백으로 변환하거나 필터를 적용할 때 NumPy를 사용할 수 있다.


In [ ]:
import numpy as np
from PIL import Image

# 이미지 로드

image = Image.open('example.jpg')
image_np = np.array(image)
print(image_np)

# 회색조 변환
gray_image_np = np.mean(image_np, axis=2).astype(np.uint8)

# 변환된 이미지 저장
gray_image = Image.fromarray(gray_image_np)
gray_image.save('example_gray.jpg')


## 유용한 함수들I


### zeros()
- zeros(): 0으로 구성된 배열을 생성한다.

In [ ]:
ar_zero = np.zeros((3,6))
print(ar_zero)

### ones()
- ones(): 1로 구성된 배열을 생성한다.

In [ ]:
ar_one = np.ones((3,6))
print(ar_one)

### np.random
- 0 ≤ 실수 < 1로 채우기: np.random.random(배열의크기)
- a ≤ 실수 < b로 채우기: np.random.uniform(a, b, 배열의크기)
- a ≤ 정수 < b로 채우기: np.random.randint(a, b, 배열의크기)

In [ ]:
print(np.random.random((2,5)))

In [ ]:
print(np.random.uniform(3.5, 4, (3,2)))

In [ ]:
print(np.random.randint(-5, 5, (2,3,4)))

- 랜덤하게 생성한 수를 가진 2차원 배열로 산포도 그래프를 그려보자.
- 산포도 그래프는 plt.scatter()로 그릴 수 있다.
- 대부분의 함수들은 많은 옵션들을 가지고 있고 scatter()함수 또한 옵션이 많다. `help(plt.scatter)`로 옵션을 확인해보기 바란다.

```
plt.scatter(x축 좌표, y축 좌표)
```

In [ ]:
import matplotlib.pyplot as plt

rd_num = np.random.randint(0,100,(50,2))
plt.scatter(rd_num[:,0], rd_num[:, 1],s=100)
plt.show()

- 2차원 배열 rd_num의 0행부터 9행까지의 배열을 확인해보자.

In [ ]:
print(rd_num[0:10])

##Problem : 랜덤데이터 배열생성
😄 다음과 같이 10이상 20미만의 임의의 정수로 채운 배열을 생성하시오.
```
[[[14 19 11 15 12 12 13 16 11]
  [12 14 18 15 11 14 18 10 10]
  [11 18 18 11 19 10 12 17 19]]

 [[13 17 17 15 18 14 16 14 13]
  [16 17 12 13 18 18 15 14 12]
  [15 18 15 16 18 16 12 18 19]]

 [[18 11 12 13 10 15 11 18 10]
  [15 16 15 15 15 12 17 11 11]
  [14 10 11 11 10 19 18 19 15]]]
```

##Problem : 랜덤데이터 배열생성
😄 다음과 같이 10이상 20미만의 임의의 실수(소수점 2자리)로 채운 배열을 생성하시오.
```
[[[11.38 18.23 10.57 16.33 13.  ]
  [14.5  16.85 16.13 17.97 17.51]]

 [[18.49 12.98 16.6  13.02 16.62]
  [13.37 19.94 16.39 11.79 11.96]]

 [[12.02 11.33 13.82 16.63 17.84]
  [17.78 14.46 18.83 11.22 13.97]]]
```

### linspace()
- linspace(): 일정한 간격으로 등분한 배열을 생성한다.

```
np.linspace(start,end,개수)
```

In [ ]:
print(np.linspace(0,15,4))

- linspace()로 생성한 배열을 선형 그래프의 y축의 값을 생성하는데 사용해보자.

In [ ]:
x = np.linspace(100000, 700000, 100)
y = 0.0012*x+700
plt.plot(x, y, ls='dashed', color='g')
plt.show()

##Problem :균등분할 배열생성
😄 110이상 120이하의 수를 5개 균등 분할하는 배열을 생성하시오.
```
[110.  112.5 115.  117.5 120. ]
```

### astype()

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
float_arr = arr.astype(float)
print(float_arr)

### ravel()
avel 함수는 다차원 배열을 1차원 배열로 평탄화한다.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

raveled = reshaped.ravel()
print(raveled)
print(reshaped) # 값이 변하지 않았음을 확인

flatten()
flatten 함수도 다차원 배열을 1차원 배열로 평탄화하지만, ravel과 달리 항상 배열의 복사본을 반환합니다

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.flatten()
print("Flattened:", flattened)
print("Oiginal array:")
print(arr)

### transpose()
- transpose(): 행과 열을 교체한다.  `배열명.T`도 가능하다.

```
np.transpose(배열명)
배열명.T
```

In [ ]:
ar= np.arange(10).reshape(2,5)
print(ar)
print('\n\n===결과===')
print(ar.T)

##Problem : 전치행렬
😄 다음과 같은 배열을 생성해 보고, 그 배열을 전치하시오.
```
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
```

```
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
 ```

## 배열과 리스트의 비교
- 얼핏 비슷해 보이지만 완전히 기능이 다른
파이썬의 리스트(list)와 numpy의 배열(array)의 차이를 간단히 비교해보자.

- 리스트와 배열의 생성에서,
  - 리스트는 정수, 실수, 문자열, 리스트 등 다양한 자료형을 담을 수 있다.
  - 배열은 정수형 또는 실수형만 담을 수 있는데 하나의 배열에는 하나의 자료형만 담을 수 있다.


In [ ]:
its_list = ['바나나', '딸기', 100, 5.5,['BTS', '블랙핑크']]
its_array = np.array([10,20,30])

  - 리스트와 배열을 출력했을 때,
    - 리스트는 대괄호안에 콤마(,)로 아이템을 구분한다.
    - 배열은 대괄호안에 구분기호 없이 공백으로만 원소를 구분한다.

In [ ]:
print(its_list)
print('========')
print(its_array)

- 리스트와 배열의 타입은,
  - 리스트는 list 타입이다.
  - 배열은 numpy.ndarray 타입이다.

In [ ]:
print(type(its_list))
print('========')
print(type(its_array))

- 리스트와 배열에 곱셈연산을 해보았을 때,
  - 리스트에서 곱셈은 리스트를 이어 붙이는 concatenate이다. 즉, 각 원소에 곱셈을 하지 않는다.
  - 배열은 각 원소에 벡터연산을 한다.


In [ ]:
print(its_list*2)
print('========')
print(its_array*2)

- 리스트와 배열의 메서드
  - 리스트와 배열은 자료형이 다르므로 지원하는 메서드의 종류도 다르다.
  - 예를 들어, 리스트에서는 mean, argmax, round 등의 메소드를 지원하지 않는다.
    - maen: 평균
    - argmax: 최대값 인덱스
    - round: 숫자를 지정한 자리수로 반올림
    - ...


- 리스트와 배열의 연산속도
  - 리스트와 배열의 연산속도를 확인해보자.
  - 억개의 숫자에 대해서 2를 곱했다.
  - 결과를 보면 배열(array)가 10배 이상 빠르다.
  - 배열은 동일한 자료형만 저장하므로 데이터 저장에 필요한 저장공간이 일정하며 연속적이다. 따라서 메모리 주소 측면에서 인덱스를 통해 빠르게 데이터에 접근할 수 있다.
  - 반면, 리스트는 다양한 자료형을 저장할 수 있어서 필요한 저장공간이 일정하지 않으며, 메모리 활동공간도 연속적이지 않다. 인덱스를 갖지만 이는 몇 번째 데이터인가 정도를 의미한다.

```python
import time
a = list(range(10 ** 8))

start = time.time()
[i *2 for i in a]
end = time.time()
print(f'리스트 실행시간: {end - start}')

a = np.array(range(10 ** 8))
start = time.time()
a * 2
end = time.time()
print(f'배열 실행시간: {end - start}')
```

